### ISSUE TITLE
does not compile with (latest) go-etherum

### ISSUE THREAD

**Issue by rsaccon** [nolash/ethereum-samples#1]
I tried to play with the examples, but it seems to require a `protocols` package which does not exist in latest `go-ethereum` codebase:
```
go run A1_Server.go
common/protocol.go:7:2: cannot find package "github.com/ethereum/go-ethereum/p2p/protocols" in any of:
....
```

**Comment by nolash** [comment]
hello, yes you are right, it needs this branch:

https://github.com/ethersphere/go-ethereum/tree/network-testing-framework

it will be merged into ethereum master over the next month.

(I wasn't really expecting there examples to be announced yet, so still some basic instructions are missing)

**Comment by avive** [comment]
hi @nolash - thanks for making this great demos available! I'm having problems building with the modified branch. I'm using go-dep https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md and my Gopkg.toml looks like:
`[[override]]
  name = "github.com/ethereum/go-ethereum"
  source = "github.com/ethersphere/go-ethereum.git"
  branch = "network-testing-framework"
  `
`deb status` shows:

`github.com/ethereum/go-ethereum`         *           branch network-testing-framework  da6a39d   893da20  58`

so it looks I'm picking up the correct branch. `$dep ensure` works fine, yet trying to build any of the samples yields an error such as:

> $go build A2_Connect.go
p2p-demo/vendor/github.com/ethereum/go-ethereum/ethclient
vendor/github.com/ethereum/go-ethereum/ethclient/ethclient.go:254: ec.c.EthSubscribe undefined (type *rpc.Client has no field or method EthSubscribe)
vendor/github.com/ethereum/go-ethereum/ethclient/ethclient.go:254: not enough arguments to return
	have (<T>)
	want (ethereum.Subscription, error)
vendor/github.com/ethereum/go-ethereum/ethclient/ethclient.go:302: ec.c.EthSubscribe undefined (type *rpc.Client has no field or method EthSubscribe)
vendor/github.com/ethereum/go-ethereum/ethclient/ethclient.go:302: not enough arguments to return
	have (<T>)
	want (ethereum.Subscription, error)`

What am I doing wrong?

**Comment by nolash** [comment]
@avive yeah it seems that network-testing-framework temporarily got broken a couple of days ago. You can use https://github.com/ethersphere/go-ethereum/tree/network-testing-framework-ethclientfix *for the purpose of these demos* until the other gets fixed. Hopefully we will merge to master soon.
