### ISSUE TITLE
Compile error: undefined: network.NewPeerPot

### ISSUE THREAD

**Issue by agazso** [nolash/ethereum-samples#2]
When I try to compile the demo programs, I get the following error:
`common/common.go:207:13: undefined: network.NewPeerPot`

I'm using `https://github.com/ethersphere/go-ethereum/tree/swarm-network-rewrite` as the `go-ethereum`.

If I change line 207 to
`	peerpot := network.NewPeerPotMap(minbinsize, addrs)`
then it seems to work after, but I'm not sure it's correct.

**Comment by nolash** [comment]
@agazso sorry I never noticed your post here. Did you resolve the issue?

**Comment by agazso** [comment]
Yes, with the change I wrote above I could run the samples.
